# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a0b0922d0758d648401910cb17e70a6c5f2c86e7642e4ded812e9838ba34887ff86789ce5ae8e41f9d8743ed6a7e771ce47f3400ce91732a39fcd56c78d9d8

test:
  secret_key_base: da8d94644cbc3f4f0447d70b7b2c980a4f100721e5fb94e4e2fa4a267be1e107563188434081b3ea9a4354ea2b42af56acc62c7d5952e97ba46cfaca43ff7832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
